In [1]:
%%time
# Import Modules
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
pd.options.display.float_format = '{:,.2f}'.format
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV
from sklearn.metrics import accuracy_score , confusion_matrix , precision_score , precision_recall_curve , f1_score
from sklearn.metrics import classification_report , roc_auc_score, recall_score
from sklearn.pipeline import Pipeline
import sklearn.metrics as metrics
from joblib import dump, load
from sklearn.decomposition import PCA
from imblearn.over_sampling import SMOTE
from sklearn.preprocessing import StandardScaler
#Import Models
from sklearn.linear_model import LogisticRegression
from sklearn import svm
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.cluster import KMeans
from sklearn.neural_network import MLPClassifier
from sklearn.ensemble import RandomForestClassifier
from imblearn.ensemble import BalancedRandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier


Using TensorFlow backend.


CPU times: user 4.02 s, sys: 1.56 s, total: 5.58 s
Wall time: 9.97 s


In [2]:
%%time
# Read csv file into dataframe
df = pd.read_csv('paysim_features.csv').drop(['Unnamed: 0'], axis=1)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6362620 entries, 0 to 6362619
Data columns (total 20 columns):
step              int64
amount            float64
ChangeOrig        float64
ChangeDest        float64
nameOrig          object
oldbalanceOrg     float64
newbalanceOrig    float64
nameDest          object
oldbalanceDest    float64
newbalanceDest    float64
isFraud           int64
isFlaggedFraud    int64
type_CASH_IN      int64
type_CASH_OUT     int64
type_DEBIT        int64
type_PAYMENT      int64
type_TRANSFER     int64
steptime          object
dayofweek         int64
timeofday         float64
dtypes: float64(8), int64(9), object(3)
memory usage: 970.9+ MB
CPU times: user 20.5 s, sys: 5.97 s, total: 26.5 s
Wall time: 27.3 s


In [3]:
df.describe()

step        amount     ChangeOrig     ChangeDest  oldbalanceOrg  \
count 6,362,620.00  6,362,620.00   6,362,620.00   6,362,620.00   6,362,620.00   
mean        243.40    179,861.90      21,230.56     124,294.73     833,883.10   
std         142.33    603,858.23     146,643.29     812,939.08   2,888,242.67   
min           1.00          0.00 -10,000,000.00 -13,060,826.21           0.00   
25%         156.00     13,389.57     -10,150.44           0.00           0.00   
50%         239.00     74,871.94           0.00           0.00      14,208.00   
75%         335.00    208,721.48           0.00     149,105.43     107,315.18   
max         743.00 92,445,516.64   1,915,267.90 105,687,838.82  59,585,040.37   

       newbalanceOrig  oldbalanceDest  newbalanceDest      isFraud  \
count    6,362,620.00    6,362,620.00    6,362,620.00 6,362,620.00   
mean       855,113.67    1,100,701.67    1,224,996.40         0.00   
std      2,924,048.50    3,399,180.11    3,674,128.94         0.04   
min              0.00            0.00            0.00         0.00   
25%              0.00            0.00            0.00         0.00   
50%              0.00      132,705.66      214,661.44         0.00   
75%        144,258.41      943,036.71    1,111,909.25         0.00   
max     49,585,040.37  356,015,889.35  356,179,278.92         1.00   

       isFlaggedFraud  type_CASH_IN  type_CASH_OUT   type_DEBIT  type_PAYMENT  \
count    6,362,620.00  6,362,620.00   6,362,620.00 6,362,620.00  6,362,620.00   
mean             0.00          0.22           0.35         0.01          0.34   
std              0.00          0.41           0.48         0.08          0.47   
min              0.00          0.00           0.00         0.00          0.00   
25%              0.00          0.00           0.00         0.00          0.00   
50%              0.00          0.00           0.00         0.00          0.00   
75%              0.00          0.00           1.00         0.00          1.00   
max              1.00          1.00           1.00         1.00          1.00   

       type_TRANSFER    dayofweek    timeofday  
count   6,362,620.00 6,362,620.00 6,362,620.00  
mean            0.08         3.12        15.32  
std             0.28         1.65         4.32  
min             0.00         0.00         0.00  
25%             0.00         2.00        12.00  
50%             0.00         3.00        16.00  
75%             0.00         4.00        19.00  
max             1.00         6.00        23.00

In [4]:
df.head()

step    amount  ChangeOrig  ChangeDest     nameOrig  oldbalanceOrg  \
0     1  9,839.64   -9,839.64        0.00  C1231006815     170,136.00   
1     1  1,864.28   -1,864.28        0.00  C1666544295      21,249.00   
2     1    181.00     -181.00        0.00  C1305486145         181.00   
3     1    181.00     -181.00  -21,182.00   C840083671         181.00   
4     1 11,668.14  -11,668.14        0.00  C2048537720      41,554.00   

   newbalanceOrig     nameDest  oldbalanceDest  newbalanceDest  isFraud  \
0      160,296.36  M1979787155            0.00            0.00        0   
1       19,384.72  M2044282225            0.00            0.00        0   
2            0.00   C553264065            0.00            0.00        1   
3            0.00    C38997010       21,182.00            0.00        1   
4       29,885.86  M1230701703            0.00            0.00        0   

   isFlaggedFraud  type_CASH_IN  type_CASH_OUT  type_DEBIT  type_PAYMENT  \
0               0             0              0           0             1   
1               0             0              0           0             1   
2               0             0              0           0             0   
3               0             0              1           0             0   
4               0             0              0           0             1   

   type_TRANSFER             steptime  dayofweek  timeofday  
0              0  1970-01-01 01:00:00          3       1.00  
1              0  1970-01-01 01:00:00          3       1.00  
2              1  1970-01-01 01:00:00          3       1.00  
3              0  1970-01-01 01:00:00          3       1.00  
4              0  1970-01-01 01:00:00          3       1.00

In [5]:
# Define X with selected columns, y as the binary variable to predict
X = df.drop(['isFraud' , 'isFlaggedFraud' , 'nameOrig' , 'nameDest' ,'steptime'] , axis = 1 ).values
y = df['isFraud'].values
# Train, Test, Split to segregate Training from Test data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=42)

In [6]:
X.shape

(6362620, 15)

In [7]:
%%time
# Replace the sklearn Pipeline with imblearn Pipeline for SMOTE
from imblearn.pipeline import Pipeline

steps = [('scaler', StandardScaler()),
         ('smote', SMOTE()),
         ('lr', LogisticRegression(class_weight='balanced'))]

model = Pipeline(steps)


# Fit it to the training data
model.fit(X_train, y_train)

model_predict = model.predict(X_test)

# Compute and print metrics
print (confusion_matrix(y_test , model_predict))
print ("Accuracy score: ", accuracy_score(y_test , model_predict))
print("F1 score: ", f1_score(y_test , model_predict))
print("Precision score: " , precision_score(y_test , model_predict))
print("Recall score: " , recall_score(y_test , model_predict))
print("ROC-AUC score: " , roc_auc_score(y_test , model_predict))
print (classification_report(y_test , model_predict))
lr = model
lr

/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


[[1823668   82683]
 [    126    2309]]
Accuracy score:  0.95661692824654
F1 score:  0.052821210838756905
Precision score:  0.02716726280120482
Recall score:  0.9482546201232033
ROC-AUC score:  0.9524411148121434
              precision    recall  f1-score   support

           0       1.00      0.96      0.98   1906351
           1       0.03      0.95      0.05      2435

    accuracy                           0.96   1908786
   macro avg       0.51      0.95      0.52   1908786
weighted avg       1.00      0.96      0.98   1908786

CPU times: user 1min 56s, sys: 10.6 s, total: 2min 6s
Wall time: 2min


Pipeline(memory=None,
         steps=[('scaler',
                 StandardScaler(copy=True, with_mean=True, with_std=True)),
                ('smote',
                 SMOTE(k_neighbors=5, kind='deprecated',
                       m_neighbors='deprecated', n_jobs=1,
                       out_step='deprecated', random_state=None, ratio=None,
                       sampling_strategy='auto', svm_estimator='deprecated')),
                ('lr',
                 LogisticRegression(C=1.0, class_weight='balanced', dual=False,
                                    fit_intercept=True, intercept_scaling=1,
                                    l1_ratio=None, max_iter=100,
                                    multi_class='warn', n_jobs=None,
                                    penalty='l2', random_state=None,
                                    solver='warn', tol=0.0001, verbose=0,
                                    warm_start=False))],
         verbose=False)

In [8]:
%%time
# Setup the pipeline
steps = [('scaler', StandardScaler()),
         ('smote', SMOTE()),
         ('rfc', RandomForestClassifier(class_weight='balanced'))]

model = Pipeline(steps)


# Fit it to the training data
model.fit(X_train, y_train)

model_predict = model.predict(X_test)

# Compute and print metrics
print (confusion_matrix(y_test , model_predict))
print ("Accuracy score: ", accuracy_score(y_test , model_predict))
print("F1 score: ", f1_score(y_test , model_predict))
print("Precision score: " , precision_score(y_test , model_predict))
print("Recall score: " , recall_score(y_test , model_predict))
print("ROC-AUC score: " , roc_auc_score(y_test , model_predict))
print (classification_report(y_test , model_predict))
rfc = model
rfc

/opt/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


[[1905545     806]
 [    162    2273]]
Accuracy score:  0.9994928713852679
F1 score:  0.8244468625317373
Precision score:  0.7382266969795388
Recall score:  0.9334702258726899
ROC-AUC score:  0.9665237143009415
              precision    recall  f1-score   support

           0       1.00      1.00      1.00   1906351
           1       0.74      0.93      0.82      2435

    accuracy                           1.00   1908786
   macro avg       0.87      0.97      0.91   1908786
weighted avg       1.00      1.00      1.00   1908786

CPU times: user 8min 14s, sys: 5.28 s, total: 8min 20s
Wall time: 8min 1s


Pipeline(memory=None,
         steps=[('scaler',
                 StandardScaler(copy=True, with_mean=True, with_std=True)),
                ('smote',
                 SMOTE(k_neighbors=5, kind='deprecated',
                       m_neighbors='deprecated', n_jobs=1,
                       out_step='deprecated', random_state=None, ratio=None,
                       sampling_strategy='auto', svm_estimator='deprecated')),
                ('rfc',
                 RandomForestClassifier(bootstrap=True, class_weight='balanced',
                                        criterion='gini', max_depth=None,
                                        max_features='auto',
                                        max_leaf_nodes=None,
                                        min_impurity_decrease=0.0,
                                        min_impurity_split=None,
                                        min_samples_leaf=1, min_samples_split=2,
                                        min_weight_fraction_lea

In [9]:
%%time
# Setup the pipeline
steps = [('scaler', StandardScaler()),
         ('smote', SMOTE()),
         ('brfc', BalancedRandomForestClassifier(class_weight='balanced'))]

model = Pipeline(steps)


# Fit it to the training data
model.fit(X_train, y_train)

model_predict = model.predict(X_test)

# Compute and print metrics
print (confusion_matrix(y_test , model_predict))
print ("Accuracy score: ", accuracy_score(y_test , model_predict))
print("F1 score: ", f1_score(y_test , model_predict))
print("Precision score: " , precision_score(y_test , model_predict))
print("Recall score: " , recall_score(y_test , model_predict))
print("ROC-AUC score: " , roc_auc_score(y_test , model_predict))
print (classification_report(y_test , model_predict))
brfc = model
brfc

[[1905300    1051]
 [     93    2342]]
Accuracy score:  0.9994006661825894
F1 score:  0.8037062457103638
Precision score:  0.690244621279104
Recall score:  0.9618069815195072
ROC-AUC score:  0.980627833233936
              precision    recall  f1-score   support

           0       1.00      1.00      1.00   1906351
           1       0.69      0.96      0.80      2435

    accuracy                           1.00   1908786
   macro avg       0.85      0.98      0.90   1908786
weighted avg       1.00      1.00      1.00   1908786

CPU times: user 1h 23min 5s, sys: 2min 20s, total: 1h 25min 25s
Wall time: 3h 13min 14s


Pipeline(memory=None,
         steps=[('scaler',
                 StandardScaler(copy=True, with_mean=True, with_std=True)),
                ('smote',
                 SMOTE(k_neighbors=5, kind='deprecated',
                       m_neighbors='deprecated', n_jobs=1,
                       out_step='deprecated', random_state=None, ratio=None,
                       sampling_strategy='auto', svm_estimator='deprecated')),
                ('brfc',
                 BalancedRandomForestClassifier(bootstrap=True,
                                                class_weight='balanced',
                                                criterion='gini',
                                                max_depth=None,
                                                max_features='auto',
                                                max_leaf_nodes=None,
                                                min_impurity_decrease=0.0,
                                                min_samples_leaf=2,
    

In [10]:
%%time
# Setup the pipeline
steps = [('scaler', StandardScaler()),
         ('smote', SMOTE()),
         ('lsvm', svm.LinearSVC(class_weight='balanced'))]

model = Pipeline(steps)


# Fit it to the training data
model.fit(X_train, y_train)

model_predict = model.predict(X_test)

# Compute and print metrics
print (confusion_matrix(y_test , model_predict))
print ("Accuracy score: ", accuracy_score(y_test , model_predict))
print("F1 score: ", f1_score(y_test , model_predict))
print("Precision score: " , precision_score(y_test , model_predict))
print("Recall score: " , recall_score(y_test , model_predict))
print("ROC-AUC score: " , roc_auc_score(y_test , model_predict))
print (classification_report(y_test , model_predict))
lsvm = model
lsvm

/opt/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


[[1820814   85537]
 [    154    2281]]
Accuracy score:  0.9551070680526785
F1 score:  0.050546796228380216
Precision score:  0.025974173859573207
Recall score:  0.9367556468172484
ROC-AUC score:  0.9459430776561369
              precision    recall  f1-score   support

           0       1.00      0.96      0.98   1906351
           1       0.03      0.94      0.05      2435

    accuracy                           0.96   1908786
   macro avg       0.51      0.95      0.51   1908786
weighted avg       1.00      0.96      0.98   1908786

CPU times: user 37min 49s, sys: 18.7 s, total: 38min 8s
Wall time: 38min 13s


Pipeline(memory=None,
         steps=[('scaler',
                 StandardScaler(copy=True, with_mean=True, with_std=True)),
                ('smote',
                 SMOTE(k_neighbors=5, kind='deprecated',
                       m_neighbors='deprecated', n_jobs=1,
                       out_step='deprecated', random_state=None, ratio=None,
                       sampling_strategy='auto', svm_estimator='deprecated')),
                ('lsvm',
                 LinearSVC(C=1.0, class_weight='balanced', dual=True,
                           fit_intercept=True, intercept_scaling=1,
                           loss='squared_hinge', max_iter=1000,
                           multi_class='ovr', penalty='l2', random_state=None,
                           tol=0.0001, verbose=0))],
         verbose=False)